### ISSUE TITLE
Start Up Instructions Produce Errors

### ISSUE THREAD

**Issue by mantisg** [marques-j-robinson/tic-tac-toe-api#2]
After executing "npm install", "cp config/default.json config/local.json", "export NODE_ENV=local", and "npm run start" respectively, this error appears.

npm ERR! Missing script: "start"
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\joshu\AppData\Local\npm-cache\_logs\2023-10-22T11_39_42_975Z-debug-0.log

If you instead execute "node app.js", a syntax error occurs concerning the export statement coupled with a warning message.

WARNING: NODE_ENV value of 'local' is ambiguous.
WARNING: See https://github.com/node-config/node-config/wiki/Strict-Mode
C:\Users\joshu\tic-tac-toe-api\models\games.js:5
export const getGame = async gameId => {
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:74:18)
    at wrapSafe (node:internal/modules/cjs/loader:1141:20)
    at Module._compile (node:internal/modules/cjs/loader:1182:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\joshu\tic-tac-toe-api\app.js:10:5)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)

I had already cloned the api from earlier iterations, but I did fetch/pull before starting that sequence of start up instructions in the README. All files should be up to date.

**Comment by marques-j-robinson** [comment]
@mantisg check out package.json
in the scripts list are the available options.
It's `dev` and not `start` readme didn't get updated with some of the changes i've been making

Also, api is a bit out of date so if you wanna run through it go for it but you'll run into some issues.
At this point might be worth it to work on your api and see if you can get a version working with a db able to save moves for multiple games.

**Comment by marques-j-robinson** [comment]
@mantisg this version has some good stuff in it though so once you're able to run it you should get some decent ideas on what it's doing and how it can translate to a flask api

**Comment by mantisg** [comment]
@marques-j-robinson Perfect, that worked. It's running with the expected output now. Thank you.

**Comment by marques-j-robinson** [comment]
@mantisg hip hip horray!
